#!/bin/bash
# PHP-FPM container entrypoint.
#
# Renders the Apache and PHP config from their templates, writes the app's
# database credentials from the environment, waits for the database, and (on a
# first run) loads the schema and content. Then hands over to Apache.
#
# Every step is idempotent: restarting the container re-renders config but never
# re-seeds a database that already has content.
set -euo pipefail

log() { printf '[entrypoint] %s\n' "$*"; }
die() { printf '[entrypoint] ERROR: %s\n' "$*" >&2; exit 1; }

# ---------------------------------------------------------------------------
# Defaults. Anything secret has no default and must be supplied.
# ---------------------------------------------------------------------------
: "${DB_HOST:=db}"
: "${DB_PORT:=3306}"
: "${DB_NAME:=afcdc_dhis}"
: "${DB_USER:=afcdc}"
: "${DB_PASSWORD:?DB_PASSWORD is required}"

: "${APP_URL:?APP_URL is required, e.g. https://dhis.africacdc.org}"
: "${APP_NAME:=Africa CDC DHIS Performance Monitor}"
: "${PHP_TIMEZONE:=Africa/Addis_Ababa}"
: "${TRUSTED_PROXY_CIDR:=172.16.0.0/12}"
: "${REQUIREMENTS_ALLOW_FROM:=127.0.0.1}"
: "${APP_DEBUG:=false}"
: "${AUTO_MIGRATE:=true}"
# Which hosts may connect to the FastCGI port. "any" is correct on a private
# compose network that publishes nothing; narrow it if the pool is exposed.
: "${FPM_ALLOWED_CLIENTS:=any}"

# APP_URL gives us both the scheme and the host the app should advertise.
APP_SCHEME="${APP_URL%%://*}"
APP_HOST="${APP_URL#*://}"; APP_HOST="${APP_HOST%%/*}"
[ "$APP_SCHEME" = "http" ] || [ "$APP_SCHEME" = "https" ] \
    || die "APP_URL must start with http:// or https:// (got '$APP_URL')"

# ---------------------------------------------------------------------------
# 1. Render config templates
# ---------------------------------------------------------------------------
render() {  # render <template> <destination> ; substitutes __NAME__ placeholders
    local src="$1" dst="$2"
    [ -f "$src" ] || die "missing template $src"
    sed -e "s|__SERVER_NAME__|${APP_HOST}|g" \
        -e "s|__TRUSTED_PROXY_CIDR__|${TRUSTED_PROXY_CIDR}|g" \
        -e "s|__REQUIREMENTS_ALLOW_FROM__|${REQUIREMENTS_ALLOW_FROM}|g" \
        -e "s|__PHP_TIMEZONE__|${PHP_TIMEZONE}|g" \
        -e "s|__FPM_ALLOWED_CLIENTS__|${FPM_ALLOWED_CLIENTS}|g" \
        "$src" > "$dst"
    # A leftover placeholder means a silently broken config; fail loudly instead.
    if grep -q '__[A-Z_]\+__' "$dst"; then
        die "unrendered placeholder in $dst: $(grep -o '__[A-Z_]\+__' "$dst" | sort -u | tr '\n' ' ')"
    fi
}
render /usr/local/etc/php/conf.d/zz-africacdc.ini.tpl \
       /usr/local/etc/php/conf.d/zz-africacdc.ini
render /usr/local/etc/php-fpm.d/zz-www.conf.tpl \
       /usr/local/etc/php-fpm.d/zz-www.conf
log "config rendered for ${APP_HOST} (${APP_SCHEME}, tz ${PHP_TIMEZONE})"

# A plain-http deployment needs two things relaxed, and both are opt-in via
# APP_URL rather than silently applied.
if [ "$APP_SCHEME" = "http" ]; then
    # 1. A Secure session cookie is never sent over http, so nobody could log in.
    sed -i 's/^session.cookie_secure.*/session.cookie_secure = 0/' \
        /usr/local/etc/php/conf.d/zz-africacdc.ini

    # The matching https-redirect suppression lives in the web container's
    # entrypoint, which owns the Apache config.
    log "WARNING: APP_URL is http, so the session cookie is not Secure."
    log "         Use https in production."
fi

# ---------------------------------------------------------------------------
# 2. Write the app's local settings from the environment
#
# app/configuration/settings.php loads settings.local.php at its end when the
# file exists. That hook is how the container injects credentials without
# baking them into the image or editing the tracked config.
# ---------------------------------------------------------------------------
php_str() { printf "'%s'" "$(printf '%s' "$1" | sed "s/\\\\/\\\\\\\\/g; s/'/\\\\'/g")"; }

cat > /var/www/html/app/configuration/settings.local.php <<PHPEOF
<?php
// GENERATED BY THE CONTAINER ENTRYPOINT ON EVERY START - DO NOT EDIT.
// Change the environment variables in .env and restart instead.
\$settings['db_master']['db_host']     = $(php_str "$DB_HOST");
\$settings['db_master']['db_port']     = $(php_str "$DB_PORT");
\$settings['db_master']['db_database'] = $(php_str "$DB_NAME");
\$settings['db_master']['db_user']     = $(php_str "$DB_USER");
\$settings['db_master']['db_password'] = base64_encode($(php_str "$DB_PASSWORD"));
PHPEOF
chown www-data:www-data /var/www/html/app/configuration/settings.local.php
chmod 640 /var/www/html/app/configuration/settings.local.php

# The tracked settings.php holds build-independent values; these few are
# environment-specific and are patched in place at start.
SETTINGS=/var/www/html/app/configuration/settings.php
sed -i \
  -e "s|^define(\"_WEB_PROTOCOL\".*|define(\"_WEB_PROTOCOL\", \"${APP_SCHEME}\");|" \
  -e "s|^define(\"_PROJECT_DOMAIN\".*|define(\"_PROJECT_DOMAIN\", \"${APP_HOST}\");|" \
  -e "s|^define(\"_DEBUG_MODE\".*|define(\"_DEBUG_MODE\", ${APP_DEBUG});|" \
  "$SETTINGS"
php -l "$SETTINGS" > /dev/null || die "settings.php is not valid PHP after substitution"
log "settings patched: ${APP_SCHEME}://${APP_HOST}, debug=${APP_DEBUG}"

# Stamp the build id so ?v= asset URLs are stable per image instead of changing
# every minute (the date() fallback in library.php::get_current_git_commit).
if [ -n "${APP_BUILD_ID:-}" ] && [ "${APP_BUILD_ID}" != "dev" ]; then
    mkdir -p /var/www/html/.git/refs/heads
    printf '%s\n' "$APP_BUILD_ID" > /var/www/html/.git/refs/heads/master
    log "asset cache-buster pinned to build ${APP_BUILD_ID}"
fi

# ---------------------------------------------------------------------------
# 3. Writable paths
# ---------------------------------------------------------------------------
mkdir -p /var/www/html/public/cache /var/www/html/public/media /var/www/html/logs
chown -R www-data:www-data /var/www/html/public/cache /var/www/html/public/media /var/www/html/logs

# ---------------------------------------------------------------------------
# 4. Wait for the database
# ---------------------------------------------------------------------------
# Debian ships the client as `mariadb` on newer releases and `mysql` on older
# ones. Pick whichever exists rather than assuming.
MYSQL_BIN=$(command -v mariadb || command -v mysql || true)
[ -n "$MYSQL_BIN" ] || die "no mariadb/mysql client in the image"

log "waiting for ${DB_HOST}:${DB_PORT} ..."
for i in $(seq 1 60); do
    if "$MYSQL_BIN" -h"$DB_HOST" -P"$DB_PORT" -u"$DB_USER" -p"$DB_PASSWORD" \
             -e "SELECT 1" "$DB_NAME" >/dev/null 2>&1; then
        log "database reachable after ${i}s"
        break
    fi
    [ "$i" -eq 60 ] && die "database not reachable after 60s"
    sleep 1
done

# ---------------------------------------------------------------------------
# 5. First-run load. Never touches a database that already has content.
# ---------------------------------------------------------------------------
if [ "$AUTO_MIGRATE" = "true" ]; then
    q() { "$MYSQL_BIN" -h"$DB_HOST" -P"$DB_PORT" -u"$DB_USER" -p"$DB_PASSWORD" \
                --default-character-set=utf8mb4 -N -B -e "$1" "$DB_NAME" 2>/dev/null; }
    load() { "$MYSQL_BIN" -h"$DB_HOST" -P"$DB_PORT" -u"$DB_USER" -p"$DB_PASSWORD" \
                   --default-character-set=utf8mb4 "$DB_NAME" < "$1" >/dev/null; }
    D=/var/www/html/db/for_upload

    tables=$(q "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='${DB_NAME}'")
    if [ "${tables:-0}" -eq 0 ]; then
        log "empty database - loading schema"
        load "$D/africacdc_dhis_schema.sql"
    else
        log "database already has ${tables} tables - skipping schema"
    fi

    deliverables=$(q "SELECT COUNT(*) FROM pm_objectives_tbl" || echo 0)
    if [ "${deliverables:-0}" -eq 0 ]; then
        log "no deliverables - loading content and tasks"
        load "$D/africacdc_dhis_seed.sql"
        load "$D/africacdc_dhis_tasks.sql"
        log "loaded $(q 'SELECT COUNT(*) FROM pm_objectives_tbl') deliverables, $(q 'SELECT COUNT(*) FROM pm_projects_tbl') activities"
    else
        log "${deliverables} deliverables already present - skipping seed"
    fi

    users=$(q "SELECT COUNT(*) FROM core_users_tbl" || echo 0)
    if [ "${users:-0}" -eq 0 ]; then
        log "NOTE: no accounts exist yet. Create one with:"
        log "      docker compose exec app php /var/www/html/tools/create-admin.php <email>"
    fi
else
    log "AUTO_MIGRATE=false - skipping schema and seed"
fi

log "starting PHP-FPM"
exec "$@"
