#!/bin/bash
# PHP-FPM container entrypoint.
#
# Renders the Apache and PHP config from their templates, writes the app's
# database credentials from the environment, waits for the database, and (on a
# first run) loads the schema and content. Then hands over to Apache.
#
# Every step is idempotent: restarting the container re-renders config but never
# re-seeds a database that already has content.
set -euo pipefail

log() { printf '[entrypoint] %s\n' "$*"; }
die() { printf '[entrypoint] ERROR: %s\n' "$*" >&2; exit 1; }

# ---------------------------------------------------------------------------
# Defaults. Anything secret has no default and must be supplied.
# ---------------------------------------------------------------------------
: "${DB_HOST:=db}"
: "${DB_PORT:=3306}"
: "${DB_NAME:=afcdc_dhis}"
: "${DB_USER:=afcdc}"
: "${DB_PASSWORD:?DB_PASSWORD is required}"

: "${APP_URL:?APP_URL is required, e.g. https://dhis.africacdc.org}"
: "${APP_NAME:=Africa CDC DHIS Performance Monitor}"
: "${PHP_TIMEZONE:=Africa/Addis_Ababa}"
: "${TRUSTED_PROXY_CIDR:=172.16.0.0/12}"
: "${REQUIREMENTS_ALLOW_FROM:=127.0.0.1}"
: "${APP_DEBUG:=false}"
: "${AUTO_MIGRATE:=true}"

# APP_URL gives us both the scheme and the host the app should advertise.
APP_SCHEME="${APP_URL%%://*}"
APP_HOST="${APP_URL#*://}"; APP_HOST="${APP_HOST%%/*}"
[ "$APP_SCHEME" = "http" ] || [ "$APP_SCHEME" = "https" ] \
    || die "APP_URL must start with http:// or https:// (got '$APP_URL')"

# ---------------------------------------------------------------------------
# 1. Render config templates
# ---------------------------------------------------------------------------
render() {  # render <template> <destination> ; substitutes __NAME__ placeholders
    local src="$1" dst="$2"
    [ -f "$src" ] || die "missing template $src"
    sed -e "s|__SERVER_NAME__|${APP_HOST}|g" \
        -e "s|__TRUSTED_PROXY_CIDR__|${TRUSTED_PROXY_CIDR}|g" \
        -e "s|__REQUIREMENTS_ALLOW_FROM__|${REQUIREMENTS_ALLOW_FROM}|g" \
        -e "s|__PHP_TIMEZONE__|${PHP_TIMEZONE}|g" \
        -e "s|__SERVER_NAME__|${APP_HOST}|g" \
        -e "s|__TRUSTED_PROXY_CIDR__|${TRUSTED_PROXY_CIDR}|g" \
        -e "s|__REQUIREMENTS_ALLOW_FROM__|${REQUIREMENTS_ALLOW_FROM}|g" \
        -e "s|__FPM_HOST__|127.0.0.1|g" \
        -e "s|__FPM_PORT__|9000|g" \
        "$src" > "$dst"
    # A leftover placeholder means a silently broken config; fail loudly instead.
    if grep -q '__[A-Z_]\+__' "$dst"; then
        die "unrendered placeholder in $dst: $(grep -o '__[A-Z_]\+__' "$dst" | sort -u | tr '\n' ' ')"
    fi
}
render /usr/local/etc/php/conf.d/zz-africacdc.ini.tpl \
       /usr/local/etc/php/conf.d/zz-africacdc.ini
cp /usr/local/etc/php-fpm.d/zz-www.conf.tpl /usr/local/etc/php-fpm.d/zz-www.conf
render /etc/nginx/templates/nginx.conf.tpl      /etc/nginx/nginx.conf
render /etc/nginx/templates/nginx-site.conf.tpl /etc/nginx/conf.d/default.conf
nginx -t || die "nginx configuration is invalid"
log "config rendered for ${APP_HOST} (${APP_SCHEME}, tz ${PHP_TIMEZONE})"

# A plain-http deployment needs two things relaxed, and both are opt-in via
# APP_URL rather than silently applied.
if [ "$APP_SCHEME" = "http" ]; then
    # 1. A Secure session cookie is never sent over http, so nobody could log in.
    sed -i 's/^session.cookie_secure.*/session.cookie_secure = 0/' \
        /usr/local/etc/php/conf.d/zz-africacdc.ini

    # (nginx does not redirect to https itself; the reverse proxy in front
    # of this container terminates TLS.)
    log "WARNING: APP_URL is http, so the session cookie is not Secure."
    log "         Use https in production."
fi

# ---------------------------------------------------------------------------
# 2. Write the app's local settings from the environment
#
# app/configuration/settings.php loads settings.local.php at its end when the
# file exists. That hook is how the container injects credentials without
# baking them into the image or editing the tracked config.
# ---------------------------------------------------------------------------
php_str() { printf "'%s'" "$(printf '%s' "$1" | sed "s/\\\\/\\\\\\\\/g; s/'/\\\\'/g")"; }

cat > /var/www/html/app/configuration/settings.local.php <<PHPEOF
<?php
// GENERATED BY THE CONTAINER ENTRYPOINT ON EVERY START - DO NOT EDIT.
// Change the environment variables in .env and restart instead.
\$settings['db_master']['db_host']     = $(php_str "$DB_HOST");
\$settings['db_master']['db_port']     = $(php_str "$DB_PORT");
\$settings['db_master']['db_database'] = $(php_str "$DB_NAME");
\$settings['db_master']['db_user']     = $(php_str "$DB_USER");
\$settings['db_master']['db_password'] = base64_encode($(php_str "$DB_PASSWORD"));
// Sign in with Microsoft (Entra ID). All three empty = feature off. See .env.example.
define('_SSO_TENANT_ID',       $(php_str "${SSO_TENANT_ID:-}"));
define('_SSO_CLIENT_ID',       $(php_str "${SSO_CLIENT_ID:-}"));
define('_SSO_CLIENT_SECRET',   $(php_str "${SSO_CLIENT_SECRET:-}"));
define('_SSO_DEFAULT_GROUP',   $(php_str "${SSO_DEFAULT_GROUP:-4}"));
define('_SSO_ALLOWED_DOMAINS', $(php_str "${SSO_ALLOWED_DOMAINS:-africacdc.org}"));
define('_SSO_AUTHORITY',       $(php_str "${SSO_AUTHORITY:-}"));
define('_SSO_REDIRECT_URI',    $(php_str "${SSO_REDIRECT_URI:-}"));
// Meaning matcher sidecar. Empty = off, and the filing suggestion falls back
// to word matching alone. See compose.matcher.yml and .env.example.
define('_MATCHER_URL',     $(php_str "${MATCHER_URL:-}"));
define('_MATCHER_WEIGHT',  $(php_str "${MATCHER_WEIGHT:-0.35}"));
define('_MATCHER_MODEL',   $(php_str "${MATCHER_MODEL:-intfloat/multilingual-e5-small}"));
PHPEOF
chown www-data:www-data /var/www/html/app/configuration/settings.local.php
chmod 640 /var/www/html/app/configuration/settings.local.php

# The tracked settings.php holds build-independent values; these few are
# environment-specific and are patched in place at start.
SETTINGS=/var/www/html/app/configuration/settings.php
sed -i \
  -e "s|^define(\"_WEB_PROTOCOL\".*|define(\"_WEB_PROTOCOL\", \"${APP_SCHEME}\");|" \
  -e "s|^define(\"_PROJECT_DOMAIN\".*|define(\"_PROJECT_DOMAIN\", \"${APP_HOST}\");|" \
  -e "s|^define(\"_DEBUG_MODE\".*|define(\"_DEBUG_MODE\", ${APP_DEBUG});|" \
  "$SETTINGS"
php -l "$SETTINGS" > /dev/null || die "settings.php is not valid PHP after substitution"
log "settings patched: ${APP_SCHEME}://${APP_HOST}, debug=${APP_DEBUG}"

# Stamp the build id so ?v= asset URLs are stable per image instead of changing
# every minute (the date() fallback in library.php::get_current_git_commit).
if [ -n "${APP_BUILD_ID:-}" ] && [ "${APP_BUILD_ID}" != "dev" ]; then
    mkdir -p /var/www/html/.git/refs/heads
    printf '%s\n' "$APP_BUILD_ID" > /var/www/html/.git/refs/heads/master
    log "asset cache-buster pinned to build ${APP_BUILD_ID}"
fi

# ---------------------------------------------------------------------------
# 3. Writable paths
# ---------------------------------------------------------------------------
mkdir -p /var/www/html/public/cache /var/www/html/public/media /var/www/html/logs /var/www/html/db/users_settings
chown -R www-data:www-data /var/www/html/db/users_settings
# public/media is a volume that outlives the image, so the brand assets the
# image ships under media/logo are hidden after the first start. The Dockerfile
# staged them in /opt/brand; refresh the volume's copy on every start so a
# logo or login background changed in git actually reaches the site.
if [ -d /opt/brand ]; then
    mkdir -p /var/www/html/public/media/logo
    cp -a /opt/brand/. /var/www/html/public/media/logo/
fi
chown -R www-data:www-data /var/www/html/public/cache /var/www/html/public/media /var/www/html/logs

# ---------------------------------------------------------------------------
# 4. Wait for the database
# ---------------------------------------------------------------------------
# Debian ships the client as `mariadb` on newer releases and `mysql` on older
# ones. Pick whichever exists rather than assuming.
MYSQL_BIN=$(command -v mariadb || command -v mysql || true)
[ -n "$MYSQL_BIN" ] || die "no mariadb/mysql client in the image"

log "waiting for ${DB_HOST}:${DB_PORT} ..."
for i in $(seq 1 60); do
    if "$MYSQL_BIN" -h"$DB_HOST" -P"$DB_PORT" -u"$DB_USER" -p"$DB_PASSWORD" \
             -e "SELECT 1" "$DB_NAME" >/dev/null 2>&1; then
        log "database reachable after ${i}s"
        break
    fi
    [ "$i" -eq 60 ] && die "database not reachable after 60s"
    sleep 1
done

# ---------------------------------------------------------------------------
# 5. First-run load. Never touches a database that already has content.
# ---------------------------------------------------------------------------
if [ "$AUTO_MIGRATE" = "true" ]; then
    q() { "$MYSQL_BIN" -h"$DB_HOST" -P"$DB_PORT" -u"$DB_USER" -p"$DB_PASSWORD" \
                --default-character-set=utf8mb4 -N -B -e "$1" "$DB_NAME" 2>/dev/null; }
    # DDL (schema load, ALTER TABLE) runs as root when DB_ROOT_PASSWORD is
    # provided, so the application's own user can be limited to
    # SELECT/INSERT/UPDATE/DELETE. Without it, the app user is used - which
    # works only while that user still holds ALTER/CREATE.
    DDL_USER="$DB_USER"; DDL_PASSWORD="$DB_PASSWORD"
    if [ -n "${DB_ROOT_PASSWORD:-}" ]; then DDL_USER="root"; DDL_PASSWORD="$DB_ROOT_PASSWORD"; fi
    log "schema changes (DDL) run as ${DDL_USER}"
    # Errors are shown, not swallowed: an operator has to see WHY an ALTER
    # failed (wrong root password, missing grant) rather than a generic line.
    qddl() {
        local out
        if ! out=$("$MYSQL_BIN" -h"$DB_HOST" -P"$DB_PORT" -u"$DDL_USER" -p"$DDL_PASSWORD" \
                      --default-character-set=utf8mb4 -N -B -e "$1" "$DB_NAME" 2>&1); then
            log "DDL as ${DDL_USER} failed: ${out}"
            return 1
        fi
        [ -z "$out" ] || printf '%s\n' "$out"
    }
    if [ "$DDL_USER" = "root" ]; then
        qddl "SELECT 1" >/dev/null || die "cannot sign in to MariaDB as root with DB_ROOT_PASSWORD - the database took its root password on its FIRST start and a later edit of .env does not change it; put the original value back in .env (or reset the root password inside the db container) and start again"
    fi
    load() { "$MYSQL_BIN" -h"$DB_HOST" -P"$DB_PORT" -u"$DDL_USER" -p"$DDL_PASSWORD" \
                   --default-character-set=utf8mb4 "$DB_NAME" < "$1" >/dev/null; }
    D=/var/www/html/db/for_upload

    # The content files DELETE every pm_* row before inserting, so they may
    # run only on a database this same start just created from the schema -
    # never because a count came back 0 on a database that already has
    # tables. That used to be the rule, and it had two holes: an operator who
    # emptied one table, or a query that simply failed (q() discards stderr,
    # so an error looked exactly like "0 rows") would reseed on a restart and
    # erase every recorded delivery.
    if ! tables=$(q "SELECT COUNT(*) FROM information_schema.tables WHERE table_schema='${DB_NAME}'") || [ -z "$tables" ]; then
        die "could not read the schema state - refusing to touch the database"
    fi
    if [ "$tables" -eq 0 ]; then
        log "empty database - loading schema"
        load "$D/africacdc_dhis_schema.sql"
        log "fresh schema - loading content and tasks"
        load "$D/africacdc_dhis_seed.sql"
        load "$D/africacdc_dhis_tasks.sql"
        log "loaded $(q 'SELECT COUNT(*) FROM pm_objectives_tbl') deliverables, $(q 'SELECT COUNT(*) FROM pm_projects_tbl') activities"
    else
        log "database already has ${tables} tables - leaving schema and content alone"
    fi

    # Idempotent migrations - each one checks before it changes, touches no
    # data rows, and is safe to run on every start.
    #
    # 1. Password hashes moved from unsalted md5(md5()) (32 chars) to
    #    password_hash() (up to 97 for Argon2id). The column was varchar(45).
    if ! pwlen=$(q "SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.COLUMNS WHERE TABLE_SCHEMA='${DB_NAME}' AND TABLE_NAME='core_users_tbl' AND COLUMN_NAME='password'") || [ -z "$pwlen" ]; then
        die "could not read core_users_tbl.password from information_schema - refusing to guess whether the migration is needed"
    fi
    if [ "$pwlen" -lt 255 ]; then
        log "widening core_users_tbl.password from varchar(${pwlen}) to varchar(255) for password_hash()"
        qddl "ALTER TABLE core_users_tbl MODIFY password VARCHAR(255) DEFAULT NULL" \
            || die "could not widen core_users_tbl.password (see the DDL error above) - check DB_ROOT_PASSWORD in .env, or run the ALTER by hand as root"
    fi

    # 2. Activities carry a budget and notes. The project page always printed
    #    "Estimated Budget" from a column that never existed, so there was no
    #    way to enter one. ADD COLUMN only when absent.
    #    AFTER kpi: the forms follow column order, so the new fields sit under
    #    "Expected task" instead of at the bottom.
    for col in "estimated_budget DOUBLE DEFAULT NULL AFTER kpi" "actual_budget DOUBLE DEFAULT NULL AFTER estimated_budget" "notes TEXT DEFAULT NULL AFTER actual_budget"; do
        name=${col%% *}
        if ! have=$(q "SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA='${DB_NAME}' AND TABLE_NAME='pm_projects_tbl' AND COLUMN_NAME='${name}'") || [ -z "$have" ]; then
            die "could not read pm_projects_tbl columns from information_schema - refusing to guess whether the migration is needed"
        fi
        if [ "$have" = "0" ]; then
            log "adding pm_projects_tbl.${name}"
            qddl "ALTER TABLE pm_projects_tbl ADD COLUMN ${col}" \
                || die "could not add pm_projects_tbl.${name} (see the DDL error above) - check DB_ROOT_PASSWORD in .env, or run the ALTER by hand as root"
        fi
    done

    # 3. Sign in with Microsoft: the Entra object id that ties an account to
    #    its Microsoft identity, and room for a full e-mail address as the
    #    username (the column was varchar(45)). Both check before changing.
    if ! have=$(q "SELECT COUNT(*) FROM information_schema.COLUMNS WHERE TABLE_SCHEMA='${DB_NAME}' AND TABLE_NAME='core_users_tbl' AND COLUMN_NAME='sso_subject'") || [ -z "$have" ]; then
        die "could not read core_users_tbl columns from information_schema - refusing to guess whether the migration is needed"
    fi
    if [ "$have" = "0" ]; then
        log "adding core_users_tbl.sso_subject"
        qddl "ALTER TABLE core_users_tbl ADD COLUMN sso_subject VARCHAR(64) DEFAULT NULL AFTER \`group\`, ADD INDEX idx_core_users_sso_subject (sso_subject)" \
            || die "could not add core_users_tbl.sso_subject (see the DDL error above) - check DB_ROOT_PASSWORD in .env, or run the ALTER by hand as root"
    fi
    if ! ulen=$(q "SELECT CHARACTER_MAXIMUM_LENGTH FROM information_schema.COLUMNS WHERE TABLE_SCHEMA='${DB_NAME}' AND TABLE_NAME='core_users_tbl' AND COLUMN_NAME='username'") || [ -z "$ulen" ]; then
        die "could not read core_users_tbl.username from information_schema - refusing to guess whether the migration is needed"
    fi
    if [ "$ulen" -lt 100 ]; then
        # The column COMMENT drives the users list (appearinlist|orderfield|...) - keep it.
        ucom=$(q "SELECT COLUMN_COMMENT FROM information_schema.COLUMNS WHERE TABLE_SCHEMA='${DB_NAME}' AND TABLE_NAME='core_users_tbl' AND COLUMN_NAME='username'" || echo "")
        ucom=$(printf '%s' "$ucom" | tr -cd 'A-Za-z0-9|=_ ')
        log "widening core_users_tbl.username from varchar(${ulen}) to varchar(100) for e-mail addresses"
        qddl "ALTER TABLE core_users_tbl MODIFY username VARCHAR(100) DEFAULT NULL COMMENT '${ucom}'" \
            || die "could not widen core_users_tbl.username (see the DDL error above) - check DB_ROOT_PASSWORD in .env, or run the ALTER by hand as root"
    fi

    # 4. Filing corrections: where people actually put things when the
    #    suggestion was wrong. Created empty; the matcher checks the table
    #    exists before reading it, so the app runs with or without it.
    if ! have=$(q "SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA='${DB_NAME}' AND TABLE_NAME='pm_filing_feedback_tbl'") || [ -z "$have" ]; then
        die "could not read information_schema.TABLES - refusing to guess whether the migration is needed"
    fi
    if [ "$have" = "0" ]; then
        log "creating pm_filing_feedback_tbl (filing corrections)"
        qddl "CREATE TABLE pm_filing_feedback_tbl (
                id INT(11) NOT NULL AUTO_INCREMENT,
                model VARCHAR(32) NOT NULL,
                words TEXT DEFAULT NULL,
                chosen_pillar_id INT(11) NOT NULL DEFAULT 0,
                chosen_objective_id INT(11) NOT NULL DEFAULT 0,
                chosen_programme_id INT(11) NOT NULL DEFAULT 0,
                suggested_pillar_id INT(11) NOT NULL DEFAULT 0,
                suggested_objective_id INT(11) NOT NULL DEFAULT 0,
                suggested_programme_id INT(11) NOT NULL DEFAULT 0,
                accepted TINYINT(1) NOT NULL DEFAULT 0,
                row_id INT(11) NOT NULL DEFAULT 0,
                user_id INT(11) NOT NULL DEFAULT 0,
                created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
                PRIMARY KEY (id),
                KEY idx_filing_feedback_model (model, accepted)
              ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4" \
            || die "could not create pm_filing_feedback_tbl (see the DDL error above) - check DB_ROOT_PASSWORD in .env, or run the CREATE by hand as root"
    fi

    # 5. Cached meaning vectors for objective and programme descriptions, so a
    #    page load only has to embed what a person just typed. Keyed by the
    #    text and the model, so an edited description recomputes itself.
    if ! have=$(q "SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA='${DB_NAME}' AND TABLE_NAME='pm_embeddings_tbl'") || [ -z "$have" ]; then
        die "could not read information_schema.TABLES - refusing to guess whether the migration is needed"
    fi
    if [ "$have" = "0" ]; then
        log "creating pm_embeddings_tbl (cached meaning vectors)"
        qddl "CREATE TABLE pm_embeddings_tbl (
                kind VARCHAR(16) NOT NULL,
                ref_id INT(11) NOT NULL,
                model VARCHAR(96) NOT NULL,
                hash CHAR(40) NOT NULL,
                vec MEDIUMBLOB NOT NULL,
                updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
                PRIMARY KEY (kind, ref_id, model)
              ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4" \
            || die "could not create pm_embeddings_tbl (see the DDL error above) - check DB_ROOT_PASSWORD in .env, or run the CREATE by hand as root"
    fi

    users=$(q "SELECT COUNT(*) FROM core_users_tbl" || echo 0)
    if [ "${users:-0}" -eq 0 ]; then
        log "NOTE: no accounts exist yet. Create one with:"
        log "      docker compose exec app php /var/www/html/tools/create-admin.php <email>"
    fi
else
    log "AUTO_MIGRATE=false - skipping schema and seed"
fi

# PHP-FPM runs as a daemon inside this same container; nginx stays in the
# foreground as PID 1. If FPM dies, /health.php starts answering 502 and the
# container health check fails - the orchestrator restarts the whole container,
# which is the recovery path a two-process container needs.
# The root password was only for schema loading and migrations above; PHP
# must never inherit it (a worker's environment is readable to anything that
# can read /proc, and clear_env is not guaranteed).
unset DB_ROOT_PASSWORD DDL_PASSWORD DDL_USER SSO_CLIENT_SECRET

log "starting PHP-FPM"
php-fpm -D
for i in 1 2 3 4 5 6 7 8 9 10; do
    php -r 'exit(@fsockopen("127.0.0.1", 9000) ? 0 : 1);' && break
    [ "$i" -eq 10 ] && die "PHP-FPM did not come up"
    sleep 1
done
log "PHP-FPM up; starting nginx"
exec "$@"
