#!/usr/bin/env python3
"""
Generate public/css/skin_africacdc.css from tools/skin-source.css.

skin-source.css is the Porto admin skin template this platform ships. Every
per-tenant skin it came with was byte-identical once colours were stripped: one
SASS-generated file with a single base colour per slot and darken()/lighten()
steps around it. This script reproduces that generator with the African Union
palette from the AfCDC Communication Style Guide, so the output keeps the exact
selector structure and shade ladder of the template.

Slot mapping (Porto slot -> AU colour):
  primary     #134B99 blue    -> #1A5632 AU Corporate Green
  secondary   #E36159 coral   -> #9F2241 AU Red
  tertiary    #2BAAB1 teal    -> #B4A269 AU Gold
  chrome      blue-grey darks -> same L and S, hue rotated onto AU green

Shade ladders are mapped by RELATIVE lightness position, not by absolute delta:
a darken(10%) step on a base at L=34 becomes the same fraction of the distance
to black on a base at L=22. That keeps every shade distinct instead of clipping
the dark end to pure black, and preserves each shade's role in the ladder.
"""
import colorsys, re, sys, pathlib
import extract_chrome

HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
SRC = HERE / "skin-source.css"   # the Porto skin template the generator re-hues
# The sidebar / top bar / logo plate are painted by the Porto BASE theme, not by
# the skin, so re-hueing the skin alone leaves them the original near-black.
CHROME_SRC = [HERE.parent / "public/css/theme.css",
              HERE.parent / "public/css/modern.css"]
DST = HERE.parent / "public/css/skin_africacdc.css"

def to_hsl(r, g, b):
    h, l, s = colorsys.rgb_to_hls(r / 255, g / 255, b / 255)
    return h * 360, s * 100, l * 100

def to_rgb(h, s, l):
    r, g, b = colorsys.hls_to_rgb((h % 360) / 360, max(0, min(100, l)) / 100, max(0, min(100, s)) / 100)
    return round(r * 255), round(g * 255), round(b * 255)

# slot: (source base hex, target base hex, hue window, min saturation)
SLOTS = {
    "primary":   ("#134b99", "#1a5632", (211, 219), 60),
    "secondary": ("#e36159", "#9f2241", (359, 7),   60),
    "tertiary":  ("#2baab1", "#b4a269", (179, 187), 50),
}
CHROME_HUE = 150.0            # AU green hue for the dark UI chrome
CHROME_WINDOW = (205, 226)
CHROME_SAT = (9, 21)

def parse(hexstr):
    h = hexstr.lstrip("#")
    if len(h) == 3:
        h = "".join(c * 2 for c in h)
    return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))

BASES = {}
for slot, (src, tgt, _, _) in SLOTS.items():
    sH, sS, sL = to_hsl(*parse(src))
    tH, tS, tL = to_hsl(*parse(tgt))
    BASES[slot] = dict(sH=sH, sS=sS, sL=sL, tH=tH, tS=tS, tL=tL)

def in_window(H, lo, hi):
    return (lo <= H <= hi) if lo <= hi else (H >= lo or H <= hi)

stats = {k: 0 for k in list(SLOTS) + ["chrome", "untouched"]}

def convert(r, g, b):
    """Map one colour through the slot ladders. Returns (r,g,b)."""
    H, S, L = to_hsl(r, g, b)
    for slot, (_, _, win, minsat) in SLOTS.items():
        B = BASES[slot]
        if S >= minsat and in_window(H, *win):
            # relative lightness: same fraction of the way to black / to white
            d = L - B["sL"]
            if d <= 0:
                nl = B["tL"] + d * (B["tL"] / B["sL"] if B["sL"] else 1)
            else:
                nl = B["tL"] + d * ((100 - B["tL"]) / (100 - B["sL"]) if B["sL"] < 100 else 1)
            # saturation scales with the base's saturation shift
            ns = S * (B["tS"] / B["sS"]) if B["sS"] else S
            stats[slot] += 1
            return to_rgb(B["tH"], ns, nl)
    if in_window(H, *CHROME_WINDOW) and CHROME_SAT[0] <= S <= CHROME_SAT[1]:
        stats["chrome"] += 1
        return to_rgb(CHROME_HUE, S, L)          # hue only; L and S untouched
    stats["untouched"] += 1
    return r, g, b

HEX_RE = re.compile(r"#([0-9a-fA-F]{6}|[0-9a-fA-F]{3})\b")
RGB_RE = re.compile(r"rgba?\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*(?:,\s*([0-9.]+)\s*)?\)")

def hex_sub(m):
    r, g, b = convert(*parse(m.group(0)))
    out = "#%02x%02x%02x" % (r, g, b)
    return out.upper() if m.group(0)[1:].isupper() or m.group(0)[1:].upper() == m.group(0)[1:] else out

def rgb_sub(m):
    r, g, b = convert(int(m.group(1)), int(m.group(2)), int(m.group(3)))
    a = m.group(4)
    return f"rgba({r}, {g}, {b}, {a})" if a is not None else f"rgb({r}, {g}, {b})"

def main():
    css = SRC.read_text()
    out = HEX_RE.sub(hex_sub, css)
    out = RGB_RE.sub(rgb_sub, out)
    header = (
        "/*!\n"
        " * Africa CDC skin for CrystalEngine (Porto admin).\n"
        " * GENERATED by tools/make_skin_africacdc.py from tools/skin-source.css.\n * Do not hand-edit: regenerate instead. Overrides go in custom.css.\n"
        " * Palette: AfCDC Communication Style Guide (African Union colours).\n"
        " *   primary   #1A5632  AU Corporate Green\n"
        " *   secondary #9F2241  AU Red\n"
        " *   tertiary  #B4A269  AU Gold\n"
        " *   chrome    deep green-grey (blue-grey hue rotated to the AU green family)\n"
        " * Project-specific overrides live in custom.css, which loads after this file.\n"
        " */\n"
    )
    src_lines, dst_lines = css.count("\n"), out.count("\n")
    if src_lines != dst_lines:
        print("  ERROR: line count changed", file=sys.stderr); sys.exit(1)

    chrome = "".join(extract_chrome.extract(str(p), hex_sub) for p in CHROME_SRC)
    chrome_header = (
        "\n\n/* ==========================================================================\n"
        "   BASE-THEME CHROME, RE-TINTED\n"
        "   Generated from theme.css and modern.css. Those two vendored files paint\n"
        "   the sidebar, top bar and logo plate with their own near-black literals,\n"
        "   which no skin file has ever touched - so without this block the chrome\n"
        "   stays slate while everything around it is AU green. The selectors below\n"
        "   are copied verbatim from the source files and carry only the colour\n"
        "   declarations, so they win purely on cascade order.\n"
        "   ========================================================================== */\n"
    )
    DST.write_text(header + out + (chrome_header + chrome if chrome.strip() else ""))

    print(f"wrote {DST}")
    print(f"  skin body:     {src_lines} lines in -> {dst_lines} lines out (unchanged)")
    print(f"  chrome block:  {chrome.count(chr(10))} lines from {len(CHROME_SRC)} base files")
    print("  colours remapped:", ", ".join(f"{k}={v}" for k, v in stats.items()))

if __name__ == "__main__":
    main()
